"use client";

import { useState } from "react";
import { CopyButton } from "@/components/CopyButton";
import type { CoverLetterOutput } from "@/lib/types";

interface RoleProps {
  mode: "role";
  resume: string;
  jd: string;
  intakeAnswers: { question: string; answer: string }[];
}

interface CompanyProps {
  mode: "company";
  resume: string;
  companyContent: string;
  companyUrl: string;
  intakeAnswers: { question: string; answer: string }[];
}

type Props = RoleProps | CompanyProps;

async function downloadCoverLetterDocx(coverLetterText: string): Promise<void> {
  const { Document, Paragraph, TextRun, Packer, AlignmentType } = await import("docx");

  const FONT = "Calibri";
  const BODY_PT = 11;

  const paragraphs = coverLetterText.split("\n").map(
    (line) =>
      new Paragraph({
        alignment: AlignmentType.LEFT,
        spacing: { after: line.trim() === "" ? 80 : 0 },
        children: [
          new TextRun({
            text: line,
            font: FONT,
            size: BODY_PT * 2,
          }),
        ],
      }),
  );

  const doc = new Document({
    title: "Cover Letter — Resume Verdict",
    description: "Cover letter generated by Resume Verdict",
    styles: {
      default: {
        document: {
          run: { font: FONT, size: BODY_PT * 2 },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
          },
        },
        children: paragraphs,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "cover-letter-resume-verdict.docx";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function CoverLetterSection(props: Props) {
  const [status, setStatus] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [output, setOutput] = useState<CoverLetterOutput | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [docxBusy, setDocxBusy] = useState(false);
  const [docxErr, setDocxErr] = useState<string | null>(null);

  async function generate() {
    setStatus("loading");
    setErrorMsg(null);
    try {
      let body: Record<string, unknown>;
      if (props.mode === "role") {
        body = {
          mode: "role",
          resume: props.resume,
          jd: props.jd,
          intakeAnswers: props.intakeAnswers,
        };
      } else {
        body = {
          mode: "company",
          resume: props.resume,
          companyContent: props.companyContent,
          companyUrl: props.companyUrl,
          intakeAnswers: props.intakeAnswers,
        };
      }

      const res = await fetch("/api/demo/cover-letter", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = (await res.json()) as {
        coverLetter?: CoverLetterOutput;
        error?: string;
      };
      if (!res.ok || !data.coverLetter) {
        throw new Error(data.error ?? `Request failed (${res.status}).`);
      }
      setOutput(data.coverLetter);
      setStatus("done");
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : "An error occurred.");
      setStatus("error");
    }
  }

  async function handleDocxDownload() {
    if (!output) return;
    setDocxBusy(true);
    setDocxErr(null);
    try {
      await downloadCoverLetterDocx(output.coverLetter);
    } catch (e) {
      setDocxErr(e instanceof Error ? e.message : "Download failed.");
    } finally {
      setDocxBusy(false);
    }
  }

  return (
    <section className="flex flex-col gap-3">
      <p className="section-label">Cover Letter</p>

      {status === "idle" && (
        <button
          onClick={generate}
          style={{ minHeight: 44 }}
          className="inline-flex w-full items-center justify-center rounded-lg border border-[#2a2a2a] bg-[#1a1a1a] px-5 py-3 text-sm font-semibold text-[#e8e4de] transition hover:bg-[#2a2a2a] sm:w-auto"
        >
          Generate Cover Letter
        </button>
      )}

      {status === "loading" && (
        <p className="text-sm text-[#a8a29e]">Writing your cover letter...</p>
      )}

      {status === "error" && (
        <div className="flex flex-col gap-2">
          <p className="rounded-lg border border-[#f87171]/30 bg-[#7f1d1d]/20 p-3 text-sm text-[#f87171]">
            {errorMsg}
          </p>
          <button
            onClick={generate}
            style={{ minHeight: 44 }}
            className="inline-flex w-fit items-center rounded-lg border border-[#2a2a2a] bg-[#1a1a1a] px-5 py-3 text-sm font-semibold text-[#e8e4de] transition hover:bg-[#2a2a2a]"
          >
            Try again
          </button>
        </div>
      )}

      {status === "done" && output && (
        <div className="flex flex-col gap-4">
          <div className="card-surface flex flex-col gap-3">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <p className="section-label">Your cover letter</p>
              <CopyButton text={output.coverLetter} />
            </div>

            <pre className="whitespace-pre-wrap font-sans text-base leading-relaxed text-[#e8e4de]">
              {output.coverLetter}
            </pre>

            <div className="flex flex-col gap-1">
              <button
                onClick={handleDocxDownload}
                disabled={docxBusy}
                style={{ minHeight: 44 }}
                className="inline-flex w-fit items-center rounded-lg border border-[#2a2a2a] bg-[#1a1a1a] px-5 py-3 text-sm font-semibold text-[#e8e4de] transition hover:bg-[#2a2a2a] disabled:opacity-60"
              >
                {docxBusy ? "Building .docx..." : "Download as .docx"}
              </button>
              {docxErr && (
                <p className="text-xs text-[#f87171]" role="alert">
                  {docxErr}
                </p>
              )}
            </div>
          </div>

          {output.keyEvidence.length > 0 && (
            <div className="card-surface">
              <p className="section-label mb-2">Evidence used</p>
              <ul className="ml-5 list-disc text-sm leading-relaxed text-[#e8e4de]">
                {output.keyEvidence.map((e, i) => (
                  <li key={i}>{e}</li>
                ))}
              </ul>
            </div>
          )}

          <p className="text-xs text-[#a8a29e]">{output.toneCheck}</p>
        </div>
      )}
    </section>
  );
}
