import type { InterviewPrep } from "./types";

export function generateInterviewPrepMarkdown(prep: InterviewPrep): string {
  const lines: string[] = [];
  lines.push("# Interview Preparation Guide");
  lines.push("");
  lines.push("*Generated by Resume Verdict — https://resumeverdict.app*");
  lines.push("");

  if (prep.likelyQuestions?.length) {
    lines.push("## Likely Questions");
    lines.push("");
    prep.likelyQuestions.forEach((q, i) => {
      lines.push(`${i + 1}. ${q}`);
    });
    lines.push("");
  }

  if (prep.starStoriesToPrep?.length) {
    lines.push("## STAR Stories to Prepare");
    lines.push("");
    prep.starStoriesToPrep.forEach((story, i) => {
      lines.push(`### Story ${i + 1}`);
      lines.push("");
      lines.push(story);
      lines.push("");
    });
  }

  if (prep.weakSpotResponses?.length) {
    lines.push("## Weak Spots to Prepare For");
    lines.push("");
    prep.weakSpotResponses.forEach((w) => {
      lines.push(`- ${w}`);
    });
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("Generated by Resume Verdict — resumeverdict.app");

  return lines.join("\n");
}
