import type {
  CompanyTailoredOutput,
  Diagnosis,
  RecruiterScan,
  TailoredOutput,
} from "./types";

export interface CheatSheetInput {
  diagnosis?: Diagnosis;
  tailored: TailoredOutput | CompanyTailoredOutput;
  recruiterScan?: RecruiterScan;
  jobTitle?: string;
  company?: string;
  mode: "role" | "company";
}

function hasKeywords(
  t: TailoredOutput | CompanyTailoredOutput,
): t is TailoredOutput {
  return "keywordsIntegrated" in t;
}

function divider(label: string): string {
  return `─── ${label} ───`;
}

function formatDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export function generateCheatSheet(input: CheatSheetInput): string {
  const lines: string[] = [];
  const date = formatDate(new Date());

  lines.push("RESUME VERDICT — APPLICATION CHEAT SHEET");
  lines.push(`Generated: ${date}`);
  if (input.jobTitle || input.company) {
    const target = [input.jobTitle, input.company ? `at ${input.company}` : ""]
      .filter(Boolean)
      .join(" ");
    lines.push(`Role: ${target}`);
  }
  lines.push("");

  if (input.mode === "role" && input.diagnosis) {
    const d = input.diagnosis;
    lines.push(divider("MATCH SUMMARY"));
    lines.push(`Overall: ${d.matchScore}/100 — ${d.verdict}`);
    lines.push(`Keyword Match:        ${d.scoreBreakdown.keywordMatch.score}/100`);
    lines.push(`Experience Relevance: ${d.scoreBreakdown.experienceRelevance.score}/100`);
    lines.push(`Trajectory Fit:       ${d.scoreBreakdown.trajectoryFit.score}/100`);
    lines.push(`ATS Parsing:          ${d.scoreBreakdown.atsParsing.score}/100`);
    lines.push("");

    if (d.verdictReasoning) {
      lines.push("Reasoning:");
      lines.push(d.verdictReasoning);
      lines.push("");
    }

    if (d.topMatches?.length) {
      lines.push(divider("TOP MATCHES (emphasize these in interviews)"));
      d.topMatches.forEach((m) => lines.push(`• ${m}`));
      lines.push("");
    }

    if (d.criticalGaps?.length) {
      lines.push(divider("GAPS TO ADDRESS (prepare answers for these)"));
      d.criticalGaps.forEach((g) => lines.push(`• ${g}`));
      lines.push("");
    }
  }

  if (hasKeywords(input.tailored)) {
    const keywordsUsed = input.tailored.keywordsIntegrated ?? [];
    const keywordsMissed = input.tailored.keywordsMissed ?? [];

    if (keywordsUsed.length) {
      lines.push(divider("KEYWORDS USED IN YOUR RESUME"));
      lines.push(keywordsUsed.join(", "));
      lines.push("");
    }

    if (keywordsMissed.length) {
      lines.push(divider("KEYWORDS NOT IN YOUR RESUME (mention verbally if possible)"));
      lines.push(keywordsMissed.join(", "));
      lines.push("");
    }
  } else {
    if (input.tailored.companyHooksUsed?.length) {
      lines.push(divider("COMPANY HOOKS USED IN YOUR OUTREACH"));
      input.tailored.companyHooksUsed.forEach((h) => lines.push(`• ${h}`));
      lines.push("");
    }
    if (input.tailored.coldOutreachAngle?.positioning) {
      lines.push(divider("POSITIONING ANGLE"));
      lines.push(input.tailored.coldOutreachAngle.positioning);
      lines.push("");
    }
    if (input.tailored.coldOutreachAngle?.draftMessage) {
      lines.push(divider("COLD OUTREACH DRAFT (for reference)"));
      lines.push(input.tailored.coldOutreachAngle.draftMessage);
      lines.push("");
    }
  }

  const prep = input.tailored.interviewPrep;
  if (prep?.likelyQuestions?.length) {
    lines.push(divider("LIKELY INTERVIEW QUESTIONS"));
    prep.likelyQuestions.forEach((q, i) => lines.push(`${i + 1}. ${q}`));
    lines.push("");
  }

  if (prep?.starStoriesToPrep?.length) {
    lines.push(divider("STAR STORIES TO PREPARE"));
    prep.starStoriesToPrep.forEach((story, i) => {
      lines.push(`Story ${i + 1}:`);
      lines.push(story);
      lines.push("");
    });
  }

  if (prep?.weakSpotResponses?.length) {
    lines.push(divider("WEAK SPOTS TO PREPARE FOR"));
    prep.weakSpotResponses.forEach((w) => lines.push(`• ${w}`));
    lines.push("");
  }

  if (input.recruiterScan) {
    const r = input.recruiterScan;
    lines.push(divider("RECRUITER'S 6-SECOND IMPRESSION"));
    lines.push(`First impression: ${r.firstImpression}`);
    lines.push(`Verdict: ${r.advanceOrReject}`);
    lines.push(`Reasoning: ${r.advanceReasoning}`);
    lines.push(`One thing to change: ${r.oneThingToChange}`);
    if (r.sixSecondScan?.noticed?.length) {
      lines.push("");
      lines.push("What the recruiter noticed:");
      r.sixSecondScan.noticed.forEach((n) => lines.push(`• ${n}`));
    }
    if (r.sixSecondScan?.redFlags?.length) {
      lines.push("");
      lines.push("Red flags identified:");
      r.sixSecondScan.redFlags.forEach((f) => lines.push(`• ${f}`));
    }
    lines.push("");
  }

  lines.push("───");
  lines.push("Generated by Resume Verdict — resumeverdict.app");

  return lines.join("\n");
}
